<h1 style="color:blue; text-align:center">Extract & Merge tables</h1>

In [4]:
###Import de librairies pour l'extraction et la transformation
import gzip
import shutil
import os
import time
import pathlib
import pickle
import feather
import pandas as pd 
import multiprocessing

In [5]:
def get_files(path, pattern):
    """
    Return the List of filenames in the <path> directory that respect
    the given <pattern> (i.e. extension)
    """
    
    list_files=[]
    currentDirectory = pathlib.Path(path)
    for currentFile in currentDirectory.glob(pattern):
        list_files.append(str(currentFile))
    return list_files

In [6]:
def extract_4Dec(path_ins, path_out, date=b"2017-12-04"):
    
    """ read all the files in the <path_ins> list
    then Keep and write only data for the given <date> in <path_out>"""
    
    with open(path_out, 'wb') as f_out:
        for path in path_ins:
            with gzip.open(path, 'rb') as f_in:
                for line in f_in:
                    if date in line: f_out.write(line)

<h2 style="color:blue; text-align:center">Processing "display" tables</h2>

In [41]:
path_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/display_12"
path_out_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/display_12.csv"
list_affichage_4dec = get_files(path_4dec, "*.gz")
extract_4Dec(path_ins=list_affichage_4dec, path_out=path_out_4dec)

<h2 style="color:blue; text-align:center">Processing "requests" tables</h2>

In [42]:
path_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/request_12"
path_out_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/request_12.csv"
list_affichage_4dec = get_files(path_4dec, "*.gz")
extract_4Dec(path_ins=list_affichage_4dec, path_out=path_out_4dec)

<h2 style="color:blue; text-align:center">Processing "clics_12" tables</h2>

In [44]:
path_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/clics_12"
path_out_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/clics_12.csv"
list_affichage_4dec = get_files(path_4dec, "*.gz")
with open(path_out_4dec, 'wb') as f_out:
    for path in list_affichage_4dec:
        with gzip.open(path, 'rb') as f_in:
            shutil.copyfileobj(f_in, f_out)

<h2 style="color:blue; text-align:center">Processing "affichage" tables</h2>

In [37]:
path_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/affichages_12"
path_out_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/affichages.csv"
list_affichage_4dec = get_files(path_4dec, "*.gz")
extract_4Dec(path_ins=list_affichage_4dec, path_out=path_out_4dec)

<h2 style="color:blue; text-align:center">Merging the 4 tables in one pandas dataFrame</h2>

**Load affichage table in pandas dataframe**

In [45]:
###Column names
cols_aff=['date_aff', 'uniq_id', 'is_mobile', 'uniq_id_widget', 'pos_widget', 'widget_width', 'widget_height']

##Specify some column types to reduce memory overflow 
col_types_aff={'is_mobile':'category', 'pos_widget':'category', 
               'widget_width':'uint16', 'widget_height':'uint16'}
##Reading options
options_aff = {
            'sep':',',
            'header':None,
            'names':cols_aff,
            'dtype':col_types_aff, 
            'index_col':False,
            'parse_dates':['date_aff'],
            'infer_datetime_format':True}

path_aff= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/affichages.csv"

df_Affichage = pd.read_csv(path_aff, **options_aff)

In [48]:
df_Affichage.head()

,date_aff,uniq_id,is_mobile,uniq_id_widget,pos_widget,widget_width,widget_height
0,2017-12-04 00:00:01,pjsle-1921681430-5a2481f03587e1.82984907,false,pjsle-1921681430-5a2481f03a52b2.96551034,pjsleads,780,419
1,2017-12-04 00:00:07,pjsle-19216814130-5a2481f680f1a3.75029244,true,pjsle-19216814130-5a2481f684db84.62324602,pjsleads,356,472
2,2017-12-04 00:00:09,pjsle-19216814130-5a2481f73fbd54.22395195,false,pjsle-19216814130-5a2481f73fe579.95228700,pjsleads,622,757
3,2017-12-04 00:00:10,pjsle-19216814134-5a2481f73434c5.39442554,false,pjsle-19216814134-5a2481f7347681.22320918,pjsleads,835,410
4,2017-12-04 00:00:10,pjsle-1921681415-5a2481f8f18e06.98170193,false,pjsle-1921681415-5a2481f8f33084.60941479,pjsleads,1000,648

**Load display table in pandas dataframe**

In [53]:
###Column names
cols_disp=['date_disp', 'uniq_id', 'pos', 'merchant_id', 'an9', "uniq_id_widget"]

##Specify some column types to reduce memory overflow 
col_types_disp={'pos':'category', 'merchant_id':'uint32'}

##Reading options
options_disp = {
            'sep':',',
            'header':None,
            'names':cols_disp,
            'dtype':col_types_disp, 
            'index_col':False,
            'parse_dates':['date_disp'],
            'infer_datetime_format':True}

path_disp= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/display_12.csv"

df_Disp = pd.read_csv(path_disp, **options_disp)

In [54]:
df_Disp.head()

,date_disp,uniq_id,pos,merchant_id,an9,uniq_id_widget
0,2017-12-04 00:00:01,pjsle-1921681415-5a2481f1368e13.99248011,1,359499,58251900;58303600;58155100,pjsle-1921681415-5a2481f1390e07.85048495
1,2017-12-04 00:00:01,pjsle-1921681415-5a2481f1368e13.99248011,2,57063793,58251900;58203000;58303600;58155100,pjsle-1921681415-5a2481f1390e07.85048495
2,2017-12-04 00:00:01,pjsle-1921681415-5a2481f1368e13.99248011,3,5795832,58251900;58203000;58303600;58155100,pjsle-1921681415-5a2481f1390e07.85048495
3,2017-12-04 00:00:02,pjsle-1921681415-5a2481f2348313.04486093,1,5981923,56051400,pjsle-1921681415-5a2481f2379246.78851340
4,2017-12-04 00:00:02,pjsle-1921681415-5a2481f2348313.04486093,2,3926636,56051400,pjsle-1921681415-5a2481f2379246.78851340

**Load request table in pandas dataframe**

In [56]:
###Column names
cols_req=['date_req', 'uniq_id', 'at_partner', 'at_pagetype', 'uniq_id_widget', 'pos_widget']

##Specify some column types to reduce memory overflow 
col_types_req={'at_pagetype':'category', 'pos_widget':'category', 'at_partner':'category'}

##Reading options
options_req = {
            'sep':',',
            'header':None,
            'names':cols_req,
            'dtype':col_types_req, 
            'index_col':False,
            'parse_dates':['date_req'],
            'infer_datetime_format':True}

path_req= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/request_12.csv"

df_Req = pd.read_csv(path_req, **options_req)

In [58]:
df_Req.head()

,date_req,uniq_id,at_partner,at_pagetype,uniq_id_widget,pos_widget
0,2017-12-04 00:00:00,pjsle-19216814134-5a2481f0261a99.37202975,Avisdedeces,LR,pjsle-19216814134-5a2481f0289c77.79748604,pjsleads
1,2017-12-04 00:00:00,pjsle-19216814134-5a2481f069d2c2.90766901,Justacote,FD,pjsle-19216814134-5a2481f069f308.49543759,pj_middle
2,2017-12-04 00:00:00,pjsle-19216814134-5a2481f069d2c2.90766901,Justacote,FD,pjsle-19216814134-5a2481f06c7e99.82505453,pj_right
3,2017-12-04 00:00:01,pjsle-19216814134-5a2481f118d804.96015430,PetitFuteUp,LR,pjsle-19216814134-5a2481f11917a7.82571839,pjsleads
4,2017-12-04 00:00:02,pjsle-19216814134-5a2481f1e4f1d6.00644870,Oubruncher,LR,pjsle-19216814134-5a2481f1e8bd41.31767876,pjsleads

**Load click table in pandas dataframe**

In [14]:
###Column names
###Column names
cols_click=['uniq_id', 'pos', 'merchant_id', 'top_annonceur', 'event_target', 'uniq_id_widget', 'pos_widget']

##Specify some column types to reduce memory overflow 
col_types_click={'pos':'category', 'merchant_id':'uint32', 'top_annonceur':'category', 
                    'event_target':'category', 'pos_widget':'category'}


##Reading options
options_click = {
            'sep':',',
            'header':None,
            'names':cols_click,
            'dtype':col_types_click, 
            'index_col':False
        }

path_click= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/clics_12.csv"

df_click = pd.read_csv(path_click, **options_click)

In [15]:
df_click.head()

,uniq_id,pos,merchant_id,top_annonceur,event_target,uniq_id_widget,pos_widget
0,pjsle-19216814134-5a27250cd3ca37.98709992,1,7860052,\N,click2call,pjsle-19216814134-5a27250cd679e8.83105518,pjsleads
1,pjsle-1921681415-5a27244c3a2864.10515859,2,1629382,1,Adresse,pjsle-1921681415-5a27244c3a52d8.55501948,pjsleads
2,pjsle-1921681415-5a2725064cc307.92537863,2,51966694,\N,Adresse,pjsle-1921681415-5a2725064cd226.35052992,pjsleads
3,pjsle-19216814134-5a2725e18fbf61.95799090,2,5473398,\N,Adresse,pjsle-19216814134-5a2725e1900d61.30525464,pjsleads
4,pjsle-1921681430-5a2725e347be41.77778799,4,1945929,1,Adresse,pjsle-1921681430-5a2725e34a1fa4.87381388,pj_middle

**Load ref_partenaire table in pandas dataframe**

In [16]:
###Column names
#cols_ref_partenaire=['at_partner', 'partenaire', 'categorie']

##Specify some column types to reduce memory overflow 
col_types_ref_partenaire={'at_partner':'category', 'partenaire':'category', 'categorie':'category'}


##Reading options
options_ref_partenaire = {
            'sep':';',
            'header':0,
            'encoding' :'ISO-8859-1', 
            'index_col':False
        }

path_ref_partenaire= "/home/alka/Documents/PROJET_FIN_ETUDES/ref_partenaire_20171201.csv"

df_ref_partenaire = pd.read_csv(path_ref_partenaire, **options_ref_partenaire)

In [17]:
df_ref_partenaire.shape

(295, 3)

In [18]:
df_ref_partenaire = df_ref_partenaire[df_ref_partenaire["categorie"]=="Annuaires"]
df_ref_partenaire.head()

   at_partner  partenaire  categorie
0      118000      118000  Annuaires
1  123cuisine  Utopia Web  Annuaires
2    123pages    123pages  Annuaires
3       3evie      Conapt  Annuaires
4   AZ-FRANCE   AZ-France  Annuaires

**Merging all the dataframes**

In [75]:
##Merge between request & ref_partenaire tables
df_dec4 = pd.merge(df_ref_partenaire, df_Req, how="inner", left_on="at_partner", right_on="at_partner")

##Merge : add click table
df_dec4 = pd.merge(df_dec4, df_click, how="left",
                   left_on=["uniq_id", "uniq_id_widget"], 
                   right_on=["uniq_id", "uniq_id_widget"])

##Merge : add affichage table
df_dec4 = pd.merge(df_dec4, df_Affichage, how="left",
                   left_on=["uniq_id", "uniq_id_widget"], 
                   right_on=["uniq_id", "uniq_id_widget"])

##Merge : add display table
df_dec4 = pd.merge(df_dec4, df_Disp, how="left",
                   left_on=["uniq_id", "uniq_id_widget"], 
                   right_on=["uniq_id", "uniq_id_widget"])

In [76]:
print(df_dec4.head())
print(df_dec4.tail())
print(df_dec4.shape )
print(df_dec4.info(memory_usage="deep"))
print(df_dec4.isnull().sum())

  at_partner partenaire  categorie            date_req  \
0     118000     118000  Annuaires 2017-12-04 00:00:11
1     118000     118000  Annuaires 2017-12-04 00:00:11
2     118000     118000  Annuaires 2017-12-04 00:00:24
3     118000     118000  Annuaires 2017-12-04 00:01:22
4     118000     118000  Annuaires 2017-12-04 00:01:29

                                     uniq_id at_pagetype  \
0  pjsle-19216814134-5a2481fae0bce4.11528640          FD
1  pjsle-19216814134-5a2481fae0bce4.11528640          FD
2  pjsle-19216814134-5a248208817cd8.31345439          FD
3  pjsle-19216814134-5a2482421eda44.12100670          FD
4  pjsle-19216814134-5a248249bfa352.91478634          FD

                              uniq_id_widget pos_widget_x pos_x  \
0  pjsle-19216814134-5a2481fae2ddd9.20270842     pjsleads   NaN
1  pjsle-19216814134-5a2481fae2ddd9.20270842     pjsleads   NaN
2  pjsle-19216814134-5a24820881c865.59860143     pjsleads   NaN
3  pjsle-19216814134-5a24824221ba81.19748565     pjsleads   NaN
4  pjsle-19216814134-5a248249bfd260.22632257     pjsleads   NaN

   merchant_id_x        ...         pos_widget_y            date_aff  \
0            NaN        ...                  NaN 2017-12-04 00:00:13
1            NaN        ...                  NaN 2017-12-04 00:00:13
2            NaN        ...                  NaN 2017-12-04 00:00:28
3            NaN        ...                  NaN                 NaT
4            NaN        ...                  NaN 2017-12-04 00:01:30

  is_mobile pos_widget widget_width widget_height           date_disp  pos_y  \
0     false   pjsleads        430.0         326.0 2017-12-04 00:00:11      1
1     false   pjsleads        430.0         326.0 2017-12-04 00:00:11      2
2      true   pjsleads        265.0         174.0 2017-12-04 00:00:24      1
3       NaN        NaN          NaN           NaN                 NaT    NaN
4      true   pjsleads        289.0         333.0 2017-12-04 00:01:29      1

  merchant_id_y                an9
0    54898299.0           58451500
1      527466.0  58451500;68050700
2    56191642.0           72257700
3           NaN                NaN
4    51917465.0           72259800

[5 rows x 22 columns]
             at_partner   partenaire  categorie            date_req  \
1951637  animaux_online  Buena-Media  Annuaires 2017-12-04 13:20:35
1951638  animaux_online  Buena-Media  Annuaires 2017-12-04 13:20:35
1951639  animaux_online  Buena-Media  Annuaires 2017-12-04 13:20:35
1951640  animaux_online  Buena-Media  Annuaires 2017-12-04 13:20:35
1951641  animaux_online  Buena-Media  Annuaires 2017-12-04 13:20:35

                                          uniq_id at_pagetype  \
1951637  pjsle-1921681415-5a253d934194d4.53258329          LR
1951638  pjsle-1921681415-5a253d934194d4.53258329          LR
1951639  pjsle-1921681415-5a253d934194d4.53258329          LR
1951640  pjsle-1921681415-5a253d934194d4.53258329          LR
1951641  pjsle-1921681415-5a253d934194d4.53258329          LR

                                   uniq_id_widget pos_widget_x pos_x  \
1951637  pjsle-1921681415-5a253d9343b779.80624643       PJHAUT   NaN
1951638  pjsle-1921681415-5a253d9343b779.80624643       PJHAUT   NaN
1951639  pjsle-1921681415-5a253d934c92e9.69669795        PJBAS   NaN
1951640  pjsle-1921681415-5a253d934c92e9.69669795        PJBAS   NaN
1951641  pjsle-1921681415-5a253d934c92e9.69669795        PJBAS   NaN

         merchant_id_x    ...    pos_widget_y            date_aff is_mobile  \
1951637            NaN    ...             NaN 2017-12-04 13:20:35     false
1951638            NaN    ...             NaN 2017-12-04 13:20:35     false
1951639            NaN    ...             NaN 2017-12-04 13:20:35     false
1951640            NaN    ...             NaN 2017-12-04 13:20:35     false
1951641            NaN    ...             NaN 2017-12-04 13:20:35     false

        pos_widget widget_width widget_height           date_disp  pos_y  \
1951637     PJHAUT        660.0         409.0 2017-12-04 13:20:35      2
1951638     PJHAUT        660.0         409.0 2017-12-04 13:20:35      3
1951639      PJBAS        660.0         409.0 2017-12-04 13:20:35      1
1951640      PJBAS        660.0         409.0 2017-12-04 13:20:35      2
1951641      PJBAS        660.0         409.0 2017-12-04 13:20:35      3

        merchant_id_y       an9
1951637      216615.0  72101100
1951638    51258320.0  72101100
1951639    53403881.0  72101100
1951640     8675220.0  72101100
1951641    50103020.0  72101100

[5 rows x 22 columns]
(1951642, 22)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1951642 entries, 0 to 1951641
Data columns (total 22 columns):
at_partner        object
partenaire        object
categorie         object
date_req          datetime64[ns]
uniq_id           object
at_pagetype       category
uniq_id_widget    object
pos_widget_x      category
pos_x             category
merchant_id_x     float64
top_annonceur     category
event_target      category
pos_widget_y      category
date_aff          datetime64[ns]
is_mobile         category
pos_widget        category
widget_width      float64
widget_height     float64
date_disp         datetime64[ns]
pos_y             category
merchant_id_y     float64
an9               object
dtypes: category(9), datetime64[ns](3), float64(4), object(6)
memory usage: 1.1 GB
None
at_partner              0
partenaire              0
categorie               0
date_req                0
uniq_id                 0
at_pagetype             0
uniq_id_widget          0
pos_widget_x            0
pos_x             1859572
merchant_id_x     1859572
top_annonceur     1859572
event_target      1859572
pos_widget_y      1859572
date_aff           184406
is_mobile          184406
pos_widget         184406
widget_width       184406
widget_height      184406
date_disp           56255
pos_y               56255
merchant_id_y       56255
an9                 56982
dtype: int64

In [77]:
###Save the data Frame
with gzip.open("/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/data_dec4.pklz","w") as f:
    pickle.dump(file=f, obj=df_dec4)

In [ ]:
##To load the dataFrame

with gzip.open("/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/data_dec4.pklz", "r") as f:
    df = pickle.load(f)

# Load data for 5, 6, 7, 8, 9, 10 december 2017

In [13]:
###dates to extract data for
dates = [b"2017-12-05", b"2017-12-06", b"2017-12-07", b"2017-12-08", b"2017-12-09", b"2017-12-10"]
##Tables to extract
tables = ["display_12", "request_12", "affichages_12"]

for date in dates:
    for table in tables:
        path_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/" + table
        path_out_4dec = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/" + table + str(date)[2:-1] + ".csv"
        list_affichage_4dec = get_files(path_4dec, "*.gz")
        extract_4Dec(path_ins=list_affichage_4dec, path_out=path_out_4dec, date=date)

# Merging dataframes for all the dates

In [20]:
###Column names
cols_aff=['date_aff', 'uniq_id', 'is_mobile', 'uniq_id_widget', 'pos_widget', 'widget_width', 'widget_height']
cols_disp=['date_disp', 'uniq_id', 'pos', 'merchant_id', 'an9', "uniq_id_widget"]
cols_req=['date_req', 'uniq_id', 'at_partner', 'at_pagetype', 'uniq_id_widget', 'pos_widget']

##Specify some column types to reduce memory overflow 
col_types_aff={'is_mobile':'category', 'pos_widget':'category', 
               'widget_width':'uint16', 'widget_height':'uint16'}
col_types_disp={'pos':'category', 'merchant_id':'uint32'}
col_types_req={'at_pagetype':'category', 'pos_widget':'category', 'at_partner':'category'}


##Reading options
options_aff = {
            'sep':',',
            'header':None,
            'names':cols_aff,
            'dtype':col_types_aff, 
            'index_col':False,
            'parse_dates':['date_aff'],
            'infer_datetime_format':True}


options_disp = {
            'sep':',',
            'header':None,
            'names':cols_disp,
            'dtype':col_types_disp, 
            'index_col':False,
            'parse_dates':['date_disp'],
            'infer_datetime_format':True}


options_req = {
            'sep':',',
            'header':None,
            'names':cols_req,
            'dtype':col_types_req, 
            'index_col':False,
            'parse_dates':['date_req'],
            'infer_datetime_format':True}


dates = [b"2017-12-05", b"2017-12-06", b"2017-12-07", b"2017-12-08", b"2017-12-09", b"2017-12-10"]

for date in dates:
    
    path_aff= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/affichages_12" + str(date)[2:-1] + ".csv"
    path_req= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/request_12" + str(date)[2:-1] + ".csv"
    path_disp= "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/display_12" + str(date)[2:-1] + ".csv"


    df_Req = pd.read_csv(path_req, **options_req)
    df_Disp = pd.read_csv(path_disp, **options_disp)
    df_Affichage = pd.read_csv(path_aff, **options_aff)

    ##Merge between request & ref_partenaire tables
    df_dec4 = pd.merge(df_ref_partenaire, df_Req, how="inner", left_on="at_partner", right_on="at_partner")

    ##Merge : add click table
    df_dec4 = pd.merge(df_dec4, df_click, how="left",
                       left_on=["uniq_id", "uniq_id_widget"], 
                       right_on=["uniq_id", "uniq_id_widget"])

    ##Merge : add affichage table
    df_dec4 = pd.merge(df_dec4, df_Affichage, how="left",
                       left_on=["uniq_id", "uniq_id_widget"], 
                       right_on=["uniq_id", "uniq_id_widget"])

    ##Merge : add display table
    df_dec4 = pd.merge(df_dec4, df_Disp, how="left",
                       left_on=["uniq_id", "uniq_id_widget"], 
                       right_on=["uniq_id", "uniq_id_widget"])

    ###Save the data Frame
    out_path = "/home/alka/Documents/PROJET_FIN_ETUDES/Data/Data4dec/data_" + str(date)[2:-1] + ".pklz"
    with gzip.open(out_path,"w") as f:
        pickle.dump(file=f, obj=df_dec4)

In [12]:
str(b"2017-12-06")[2:-1]

'2017-12-06'